### ISSUE TITLE
HS105 "module not support" + timeout

### ISSUE THREAD

**Issue by tedder** [GadgetReactor/pyHS100#38]
python 3.6, OSX Sierra (er, MacOS Sierra), pyHS100 0.2.3, which should support the HS105 per #18 and #30:

```
$ pip3 show pyHS100
Name: pyHS100
Version: 0.2.3

$ python3 examples/discover.py
DEBUG:pyHS100.protocol:Sending discovery to 255.255.255.255:9999
DEBUG:pyHS100.protocol:Waiting 5 seconds for responses...
ERROR:pyHS100.protocol:Got exception timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyHS100/protocol.py", line 99, in discover
    data, addr = sock.recvfrom(4096)
socket.timeout: timed out
Found device!
{'ip': '192.168.0.221',
 'port': 9999,
 'sys_info': {'emeter': {'err_code': -1, 'err_msg': 'module not support'},
              'system': {'get_sysinfo': {'active_mode': 'schedule',
                                         'alias': 'TV lamp',
                                         'dev_name': 'Smart Wi-Fi Plug Mini',
                                         'deviceId': '800630A6D01BE4Axxxxx',
                                         'err_code': 0,
                                         'feature': 'TIM',
                                         'fwId': '00000000000000000000000000000000',
                                         'hwId': 'E5D7E6089B060EFxxxxxx',
                                         'hw_ver': '1.0',
                                         'icon_hash': '',
                                         'latitude_i': 45xxx,
                                         'led_off': 0,
                                         'longitude_i': -122xxx,
                                         'mac': '50:C7:BF:xxxxx',
                                         'model': 'HS105(US)',
                                         'oemId': '003E098AF0D44D4BAB7xxxxxxxx',
                                         'on_time': 0,
                                         'relay_state': 0,
                                         'rssi': -61,
                                         'sw_ver': '1.0.6 Build 160722 '
                                                   'Rel.081616',
                                         'type': 'IOT.SMARTPLUGSWITCH',
                                         'updating': 0}}}}

$ python3 examples/cli.py 192.168.0.221
DEBUG:pyHS100.protocol:> (31) {"system": {"get_sysinfo": {}}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyHS100/pyHS100.py", line 99, in _query_helper
    request={target: {cmd: arg}}
  File "/usr/local/lib/python3.6/site-packages/pyHS100/protocol.py", line 59, in query
    sock.shutdown(socket.SHUT_RDWR)
OSError: [Errno 57] Socket is not connected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/cli.py", line 15, in <module>
    logging.info("Identify: %s", hs.identify())
  File "/usr/local/lib/python3.6/site-packages/pyHS100/pyHS100.py", line 317, in identify
    info = self.sys_info
  File "/usr/local/lib/python3.6/site-packages/pyHS100/pyHS100.py", line 119, in sys_info
    return self.get_sysinfo()
  File "/usr/local/lib/python3.6/site-packages/pyHS100/pyHS100.py", line 171, in get_sysinfo
    return self._query_helper("system", "get_sysinfo")
  File "/usr/local/lib/python3.6/site-packages/pyHS100/pyHS100.py", line 102, in _query_helper
    raise SmartPlugException(ex) from ex
pyHS100.pyHS100.SmartPlugException: [Errno 57] Socket is not connected

$ telnet 192.168.0.221 9999
Trying 192.168.0.221...
Connected to 192.168.0.221.
Escape character is '^]'.
```

**Comment by tedder** [comment]
@trainman419 I think this is the timeout you saw in #19. Hmm. It appears the only problem is with `discover`; `cli` works, I wonder if it's the order-of-operations and a socket cleanup issue.

**Comment by kirichkov** [comment]
I believe discover is supposed to time out - check this comment: https://github.com/GadgetReactor/pyHS100/pull/25#issuecomment-271159639

**Comment by tedder** [comment]
"module not support" is wrong though, yeah?

**Comment by tedder** [comment]
hmm, "not support" is about having the emeter (sounds like scientology). HS105 doesn't have the meter, so .. I guess there's nothing wrong? I don't know why I was getting the socket errors, though.

**Comment by kirichkov** [comment]
"Not support" is returned from the plug :-) I think it's not Scientology. To me it sounds like google-translate English ;-)

getting the socket timeouts is the expected behavior. Read the link to the comment, it's explained there.

**Comment by mweinelt** [comment]
HS105 support landed in master as per https://github.com/GadgetReactor/pyHS100/pull/30#issuecomment-273022201.

Please update to a more recent version, which might need git at this time.
