### ISSUE TITLE
LB100 Command Line Test Errors

### ISSUE THREAD

**Issue by Segfault198** [GadgetReactor/pyHS100#48]
Trying to figure out if I'm missing something or if its a problem with the module. Any time I run the command line test against a light I get the error trace below.  Any thoughts?

./pyhs100 --ip 192.168.1.93
== Couch Lamp - LB100(US) ==
Traceback (most recent call last):
  File "./pyhs100", line 11, in <module>
    load_entry_point('pyHS100==0.2.4.1', 'console_scripts', 'pyhs100')()
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/pyHS100/cli.py", line 34, in cli
    ctx.invoke(state)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/pyHS100/cli.py", line 62, in state
    click.echo(click.style("Device state: %s" % plug.state,
  File "/srv/homeassistant/lib/python3.4/site-packages/pyHS100/pyHS100.py", line 668, in state
    relay_state = self.sys_info['relay_state']
KeyError: 'relay_state'

**Comment by rytilahti** [comment]
The state command of the console tool tries currently to interface with a plug and therefore it fails here. You can try other commands (see --help) from which some may work currently.

For developers, the proper fix here is to make the tool to use SmartDevice directly and/or use a specific implementation based on some information gathered from the device.

**Comment by rytilahti** [comment]
Could you test with #50?

To use the bulb-specific commands (hsv, brightness, temperature) you have to pass ```--bulb``` option, the basic functionality should work without it.

**Comment by Segfault198** [comment]
Yeah might take me a bit. I'll get back to you with the results. Thanks!
