### ISSUE TITLE
HS105 Testing

### ISSUE THREAD

**Issue by mcheavens** [GadgetReactor/pyHS100#66]
First let me thank all to have contributed. Installed via pip. I am testing some HS105's and deciding whether to try to incorporate instead of a LOT of Insteon devices. I have two units on the same subnet and have done some testing from both the local subnet and on a different subnet. I see errors on both, but from a basic level I can turn them on and off! I thought the errors were related to no lat/lon, but that is not the case as you can see below. Curious what might be the cause of the traceback errors and whether I should or should not be able to run from a remote subnet all the commands?

Thanks,
Mark

Here are the results from the local subnet:
Only works when on the local subnet...Testing a HS105
Running arp -n | grep 50:c7:bf | cut -d' ' -f1
10.50.10.134
10.50.10.184
Running pyhs100 discover
Discovering devices for 5 seconds
Found device: {'ip': '10.50.10.184',
 'port': 9999,
 'sys_info': {'emeter': {'get_realtime': {'err_code': -1,
                                          'err_msg': 'module not support'}},
              'system': {'get_sysinfo': {'active_mode': 'none',
                                         'alias': 'Test Unit',
                                         'dev_name': 'Smart Wi-Fi Plug '
                                                     'Mini',
                                         'deviceId': '8006F7570EE99A00308CFFFF27C81B591875827E',
                                         'err_code': 0,
                                         'feature': 'TIM',
                                         'fwId': '00000000000000000000000000000000',
                                         'hwId': 'E5D7E6089B060EF662783C23AE110522',
                                         'hw_ver': '1.0',
                                         'icon_hash': '',
                                         'latitude_i': 306248,
                                         'led_off': 0,
                                         'longitude_i': -975717,
                                         'mac': '50:C7:BF:5F:DC:03',
                                         'model': 'HS105(US)',
                                         'oemId': '003E098AF0D44D4BAB796B3F6A7A830E',
                                         'on_time': 0,
                                         'relay_state': 0,
                                         'rssi': -44,
                                         'sw_ver': '1.2.1 Build 170406 '
                                                   'Rel.135348',
                                         'type': 'IOT.SMARTPLUGSWITCH',
                                         'updating': 0}}}}
Running pyhs100 --ip 10.50.10.184 sysinfo
== System info ==
{'active_mode': 'none',
 'alias': 'Test Unit',
 'dev_name': 'Smart Wi-Fi Plug Mini',
 'deviceId': '8006F7570EE99A00308CFFFF27C81B591875827E',
 'feature': 'TIM',
 'fwId': '00000000000000000000000000000000',
 'hwId': 'E5D7E6089B060EF662783C23AE110522',
 'hw_ver': '1.0',
 'icon_hash': '',
 'latitude_i': 306248,
 'led_off': 0,
 'longitude_i': -975717,
 'mac': '50:C7:BF:5F:DC:03',
 'model': 'HS105(US)',
 'oemId': '003E098AF0D44D4BAB796B3F6A7A830E',
 'on_time': 0,
 'relay_state': 0,
 'rssi': -45,
 'sw_ver': '1.2.1 Build 170406 Rel.135348',
 'type': 'IOT.SMARTPLUGSWITCH',
 'updating': 0}
Running pyhs100 --ip 10.50.10.184 on
Turning on..
Running pyhs100 --ip 10.50.10.184 off
Turning off..
Running pyhs100 --ip 10.50.10.184 state
== Test Unit - HS105(US) ==
Device state: OFF
LED state:    True
Time:         2017-06-25 19:51:15
On since:     2017-06-25 19:51:41.059299
Hardware:     1.0
Software:     1.2.1 Build 170406 Rel.135348
MAC (rssi):   50:C7:BF:5F:DC:03 (-45)
Traceback (most recent call last):
  File "/usr/local/bin/pyhs100", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pyHS100/cli.py", line 70, in state
    click.echo("Location:     %s" % plug.location)
  File "/usr/local/lib/python3.4/dist-packages/pyHS100/pyHS100.py", line 251, in location
    return {"latitude": info["latitude"],
KeyError: 'latitude'
Running pyhs100 --ip 10.50.10.184 emeter NOTE: HS105's do not have emeter
== Emeter ==
Device has no emeter
Running pyhs100 --ip 10.50.10.184 led
LED state: True

And from a remote subnet the same commands to the same device.
Only works when on the local subnet...Testing a HS105
Running arp -n | grep 50:c7:bf | cut -d' ' -f1
Running pyhs100 discover
Discovering devices for 5 seconds
Running pyhs100 --ip 10.50.10.184 sysinfo
== System info ==
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 71, in _query_helper
    request={target: {cmd: arg}}
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/protocol.py", line 58, in query
    chunk = sock.recv(4096)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pyhs100", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/cli.py", line 51, in sysinfo
    click.echo(pformat(plug.sys_info))
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 91, in sys_info
    return self.get_sysinfo()
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 101, in get_sysinfo
    return self._query_helper("system", "get_sysinfo")
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 74, in _query_helper
    raise_from(SmartPlugException(), ex)
  File "/usr/local/lib/python3.5/dist-packages/future/utils/__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
pyHS100.pyHS100.SmartPlugException
Running pyhs100 --ip 10.50.10.184 on
Turning on..
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 71, in _query_helper
    request={target: {cmd: arg}}
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/protocol.py", line 58, in query
    chunk = sock.recv(4096)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pyhs100", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/cli.py", line 119, in on
    plug.turn_on()
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 724, in turn_on
    self._query_helper("system", "set_relay_state", {"state": 1})
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 74, in _query_helper
    raise_from(SmartPlugException(), ex)
  File "/usr/local/lib/python3.5/dist-packages/future/utils/__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
pyHS100.pyHS100.SmartPlugException
Running pyhs100 --ip 10.50.10.184 off
Turning off..
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 71, in _query_helper
    request={target: {cmd: arg}}
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/protocol.py", line 58, in query
    chunk = sock.recv(4096)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pyhs100", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/cli.py", line 127, in off
    plug.turn_off()
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 732, in turn_off
    self._query_helper("system", "set_relay_state", {"state": 0})
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 74, in _query_helper
    raise_from(SmartPlugException(), ex)
  File "/usr/local/lib/python3.5/dist-packages/future/utils/__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
pyHS100.pyHS100.SmartPlugException
Running pyhs100 --ip 10.50.10.184 state
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 71, in _query_helper
    request={target: {cmd: arg}}
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/protocol.py", line 58, in query
    chunk = sock.recv(4096)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pyhs100", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/cli.py", line 59, in state
    click.echo(click.style("== %s - %s ==" % (plug.alias, plug.model),
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 136, in alias
    return self.sys_info['alias']
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 91, in sys_info
    return self.get_sysinfo()
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 101, in get_sysinfo
    return self._query_helper("system", "get_sysinfo")
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 74, in _query_helper
    raise_from(SmartPlugException(), ex)
  File "/usr/local/lib/python3.5/dist-packages/future/utils/__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
pyHS100.pyHS100.SmartPlugException
Running pyhs100 --ip 10.50.10.184 emeter NOTE: HS105's do not have emeter
== Emeter ==
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 71, in _query_helper
    request={target: {cmd: arg}}
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/protocol.py", line 58, in query
    chunk = sock.recv(4096)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pyhs100", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/cli.py", line 84, in emeter
    if not plug.has_emeter:
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 742, in has_emeter
    return SmartPlug.FEATURE_ENERGY_METER in self.features
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 752, in features
    features = self.sys_info['feature'].split(':')
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 91, in sys_info
    return self.get_sysinfo()
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 101, in get_sysinfo
    return self._query_helper("system", "get_sysinfo")
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 74, in _query_helper
    raise_from(SmartPlugException(), ex)
  File "/usr/local/lib/python3.5/dist-packages/future/utils/__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
pyHS100.pyHS100.SmartPlugException
Running pyhs100 --ip 10.50.10.184 led
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 71, in _query_helper
    request={target: {cmd: arg}}
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/protocol.py", line 58, in query
    chunk = sock.recv(4096)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pyhs100", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/cli.py", line 111, in led
    click.echo("LED state: %s" % plug.led)
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 769, in led
    return bool(1 - self.sys_info["led_off"])
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 91, in sys_info
    return self.get_sysinfo()
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 101, in get_sysinfo
    return self._query_helper("system", "get_sysinfo")
  File "/usr/local/lib/python3.5/dist-packages/pyHS100/pyHS100.py", line 74, in _query_helper
    raise_from(SmartPlugException(), ex)
  File "/usr/local/lib/python3.5/dist-packages/future/utils/__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
pyHS100.pyHS100.SmartPlugException

**Comment by rytilahti** [comment]
The issue with location has been fixed in git, but there has been no releases sofar. If you want, you can install the newest git with pip to see if it helps. There is no reason why controlling should not work on devices in other networks, discovery on the other hand is broadcast-based and will not be available there.

**Comment by mcheavens** [comment]
I don't know how to get the latest version from git, but I did find the relevant change needed in pyHS100.py and changed it. That did correct the issue in status.
- Maybe add some self check by looking for local subnet and exit cleanly if IP used is not subnet and therefore broadcast would not work. Just an idea.

        info = self.sys_info
        loc = {"latitude": None,
               "longitude": None}

        if "latitude" in info and "longitude" in info:
            loc["latitude"] = info["latitude"]
            loc["longitude"] = info["longitude"]
        elif "latitude_i" in info and "longitude_i" in info:
            loc["latitude"] = info["latitude_i"]
            loc["longitude"] = info["longitude_i"]
        else:
            _LOGGER.warning("Unsupported device location.")

        return loc

**Comment by rytilahti** [comment]
For discovery one should not define an IP at all, so I think having a check for broadcasting would be superfluous. Here's the documentation on how to use pip with version control systems: https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support . The piece of code you found is indeed correct, are you having any other issues with your HS105 now?

**Comment by rytilahti** [comment]
I think this can be closed, please reopen / create a new issue if needed.
