### ISSUE TITLE
Query State failed on HS100

### ISSUE THREAD

**Issue by Semant1ka** [GadgetReactor/pyHS100#67]
Hi,
I've run the utility with my smart plug and got this exception on query state.
In order to make discovery working, I've changed target field in TPLinkSmartHomeProtocol.discover to my custom wlan0 broadcast network value.

== My Smart Plug - HS100(EU) ==
Device state: ON
LED state: True
On since: 2017-06-16 09:35:45.934023
== Generic information ==
Time:         1970-01-14 23:19:24
Hardware:     1.0
Software:     1.0.8 Build 151101 Rel.24452
Traceback (most recent call last):
  File "/usr/local/bin/pyhs100", line 9, in <module>
    load_entry_point('pyHS100==0.2.4.2', 'console_scripts', 'pyhs100')()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pyHS100-0.2.4.2-py3.4.egg/pyHS100/cli.py", line 80, in state
    click.echo("MAC (rssi):   %s (%s)" % (dev.mac, dev.rssi))
  File "/usr/local/lib/python3.4/dist-packages/pyHS100-0.2.4.2-py3.4.egg/pyHS100/pyHS100.py", line 302, in rssi
    return self.sys_info["rssi"]
KeyError: 'rssi'

I am suspecting that I am doing something wrong, because it seems nobody encountered this issue before.

**Comment by rytilahti** [comment]
Can you please post your 'pyhs100 sysinfo'? Looks like it's missing rssi information for some reason.

**Comment by Semant1ka** [comment]
Sorry for the delay, here is pyhs100 sysinfo output

== System info ==
{'active_mode': 'schedule',
 'alias': 'My Smart Plug',
 'dev_name': 'Wi-Fi Smart Plug',
 'deviceId': '80061E93E28EEBA9FA1929D15C4678C7172A8AF2',
 'feature': 'TIM',
 'fwId': 'BFF24826FBC561803E49379DBE74FD71',
 'hwId': '22603EA5E716DEAEA6642A30BE87AFCA',
 'hw_ver': '1.0',
 'icon_hash': '',
 'latitude': 55.836014,
 'led_off': 0,
 'longitude': 37.482775,
 'mac': '50:C7:BF:01:E5:3E',
 'model': 'HS100(EU)',
 'oemId': '812A90EB2FCF306A993FAD8748024B07',
 'on_time': 255419,
 'relay_state': 1,
 'sw_ver': '1.0.8 Build 151101 Rel.24452',
 'type': 'smartplug',
 'updating': 0}

**Comment by rytilahti** [comment]
Thanks, looks like it has no rssi information at all, I made a PR which fixes this (displays just None on status for it). Also added an example to `fakes.py` for future reference.

**Comment by rytilahti** [comment]
Merged.

**Comment by Semant1ka** [comment]
Finally was able to test on the device - fix works, thanks
