### ISSUE TITLE
KeyError: u'latitude'

### ISSUE THREAD

**Issue by nadigo** [GadgetReactor/pyHS100#69]
Hi, 

when running  pyhs100 --ip 192.168.0.6 state  on Rasberbey Pi I'm getting the below error, 

seems like parsing issue?

Nadav

pi@raspberrypi:~ $ sudo pyhs100 --ip 192.168.0.6 state
== Livingroom Light - HS105(US) ==
Device state: ON
LED state:    True
Time:         2017-07-22 22:11:07
On since:     2017-07-23 01:53:54.183459
Hardware:     1.0
Software:     1.2.1 Build 170406 Rel.135348
MAC (rssi):   50:C7:BF:7D:56:54 (-22)
Traceback (most recent call last):
  File "/usr/local/bin/pyhs100", line 9, in <module>
    load_entry_point('pyHS100==0.2.4.2', 'console_scripts', 'pyhs100')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyHS100/cli.py", line 70, in state
    click.echo("Location:     %s" % plug.location)
  File "/usr/local/lib/python2.7/dist-packages/pyHS100/pyHS100.py", line 251, in location
    return {"latitude": info["latitude"],
KeyError: u'latitude'

**Comment by rytilahti** [comment]
Closed with #72.
